server:
  port: ${SERVER_PORT}

spring:
  application:
    name: gorogoro-cart

  servlet:
    encoding:
      charset: UTF-8
      force: true

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  cloud:
    openfeign:
      client:
        config:
          course-service:
            url: ${COURSE_SERVICE_URL}

  rabbitmq:
    host: ${SANSEONG_IP}
    port: 5672
    username: ${RABBIT_ID}
    password: ${RABBIT_PASSWORD}
    virtual-host: ${VHOST}

rabbit:
  events:
    exchange: lxp.events
    routing-prefix: lxp.
    queues:
      course-deleted:
        name: cart.course.deleted.q
        bindings:
          - lxp.course.deleted
      user-deleted:
        name: cart.user.deleted.q
        bindings:
          - lxp.user.deleted
    dlq:
      dlx: lxp.events.dlx
      name: lxp.events.dlq
      routing: lxp.events.dlq

resilience4j:
  circuitbreaker:
    instances:
      courseClient:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  timelimiter:
    instances:
      courseClient:
        timeoutDuration: 3s
